import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { ThemeProvider } from "../../contexts/ThemeContext";
import { UserAdminProvider } from "@/contexts/UserAdminContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserAdminProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={`${inter.className} flex`}>
            <Navbar />
            <main className="ml-64 min-h-screen w-full">{children}</main>
          </body>
        </html>
      </ThemeProvider>
    </UserAdminProvider>
  );
}
